
services:
  my-sql:
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3  
    networks:
      - my_network 
    
  my-node:
    build:
      context: ./node
    container_name: mynode  
    networks:
      - my_network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "8180:8180"
    depends_on:
      my-sql:
        condition: service_healthy
    command: "node index.js"

  my-nginx:
    build:
      context: ./nginx
    container_name: meunginx
    ports:
      - "8080:80"
    networks:
      - my_network
    depends_on:
      - my-node
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
